### ISSUE TITLE
"Protobuf gencode version 5.27.2 is older than the runtime version 5.28.2" (Mac OS)

### ISSUE THREAD

**Issue by phuddha** [IRL2/nanover-server-py#248]
Gpoing through a clean developer installation on Mac OS - following readme. 

On running tests ( python -m pytest python-libraries) there is 1 failure and 6 warnings:

FAILED python-libraries/nanover-essd/tests/test_essd_client_server.py::test_remove_service - AssertionError: assert ServiceHub(**{'name': 'test service', 'address': '192.168.0.7', 'services': {'trajectory': 54321, 'imd': 54322, 'multiplayer': 54323, 'builder': 54324...

--- warnings ---

../../../../../opt/anaconda3/envs/nanover-dev/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112
  /opt/anaconda3/envs/nanover-dev/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.2 is older than the runtime version 5.28.2 at nanover/protocol/command/command_service.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
    warnings.warn(

../../../../../opt/anaconda3/envs/nanover-dev/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112
  /opt/anaconda3/envs/nanover-dev/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.2 is older than the runtime version 5.28.2 at nanover/protocol/state/state_service.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
    warnings.warn(

../../../../../opt/anaconda3/envs/nanover-dev/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112
  /opt/anaconda3/envs/nanover-dev/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.2 is older than the runtime version 5.28.2 at nanover/protocol/trajectory/get_frame.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
    warnings.warn(

../../../../../opt/anaconda3/envs/nanover-dev/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112
  /opt/anaconda3/envs/nanover-dev/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.2 is older than the runtime version 5.28.2 at nanover/protocol/trajectory/frame.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
    warnings.warn(

../../../../../opt/anaconda3/envs/nanover-dev/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112
  /opt/anaconda3/envs/nanover-dev/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.2 is older than the runtime version 5.28.2 at nanover/protocol/array.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
    warnings.warn(

../../../../../opt/anaconda3/envs/nanover-dev/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112
  /opt/anaconda3/envs/nanover-dev/lib/python3.12/site-packages/google/protobuf/runtime_version.py:112: UserWarning: Protobuf gencode version 5.27.2 is older than the runtime version 5.28.2 at nanover/protocol/trajectory/trajectory_service.proto. Please avoid checked-in Protobuf gencode that can be obsolete.
    warnings.warn(

**Comment by Ragzouken** [comment]
The test failure is potentially fixed by https://github.com/IRL2/nanover-protocol/pull/249 -- could you try again on main?

**Comment by phuddha** [comment]
Went through a completely fresh install, compile and test on main.  Test passes now. Protobuf deprecation warnings are still there.

**Comment by Ragzouken** [comment]
Try again on this branch to see if the warnings are addressed: https://github.com/IRL2/nanover-protocol/pull/252

**Comment by phuddha** [comment]
Still getting the same warnings on branch fix/grpc-update. 

After switching to the new branch I ran 

./compile.sh --no-dotnet 
and then 
python -m pytest python-libraries

Now retrying with a full fresh reinstall.

**Comment by phuddha** [comment]
Rebuilt fresh dev environment and ran compile and test on branch. Still getting same warnings.

**Comment by Ragzouken** [comment]
Closing as this hasn't been a blocker for anyone, and we will discontinue using gRPC in the future.
